const courses=[
{title:'קורס מסחר באופציות: רמה 1 – אופציות CALL מנקודת מבט של הקונה',link:'https://trade2.co.il/courses/option1/',categories:['אופציות','אופציות למתחילים'],level:'מתחילים',duration:'5 שעות',students:'2545',image:'https://trade2.co.il/wp-content/uploads/2024/11/87-3-1-1024x696.png'},
{title:'אסטרטגיה באופציות במהלך דוחות כספיים',link:'https://trade2.co.il/courses/',categories:['אופציות','אסטרטגיות'],level:'מתקדמים',duration:'2 שעות ו-50 דקות',students:'1264',image:'https://trade2.co.il/wp-content/uploads/2024/10/87-4-1-1024x696.png'},
{title:'אסטרטגיית Covered Call',link:'https://trade2.co.il/courses/',categories:['אופציות','אסטרטגיות למתקדמים'],level:'ביניים',duration:'5 שעות ו-5 דקות',students:'1565',image:'https://trade2.co.il/wp-content/uploads/2024/10/87-4-1-1024x696.png'},
{title:'קורס מסחר באופציות: רמה 6 – תנודתיות ווגא',link:'https://trade2.co.il/courses/',categories:['אופציות','אופציות למתחילים'],level:'מתחילים',duration:'2 שעות ו-11 דקות',students:'1836',image:'https://trade2.co.il/wp-content/uploads/2024/10/87-5-1-770x300.png'},
{title:'קורס אופציות אסטרטגיית Calendar Spread',link:'https://trade2.co.il/courses/',categories:['אופציות','אסטרטגיות'],level:'ביניים',duration:'2 שעות ו-55 דקות',students:'15',image:'https://trade2.co.il/wp-content/uploads/2024/10/87-4-1-1024x696.png'},
{title:'קורס אופציות לסחור עם הכסף המוסדי',link:'https://trade2.co.il/courses/',categories:['אופציות','אסטרטגיות'],level:'מתקדמים',duration:'שעתיים ו-4 דקות',students:'1491',image:'https://trade2.co.il/wp-content/uploads/2024/10/87-4-1-1024x696.png'}
];
const grid=document.getElementById('courseGrid');
if(grid)grid.innerHTML=courses.map(c=>`<a class="course-card" href="${c.link}" target="_blank" rel="noopener"><div class="course-img" style="background-image:url('${c.image}')"></div><div class="course-body"><span class="tag">${c.categories[0]} • ${c.level}</span><h3>${c.title}</h3><div class="course-meta"><span>${c.duration}</span><span>${Number(c.students).toLocaleString('he-IL')} תלמידים</span></div></div></a>`).join('');
