const L=[
["יסודות תטא","מהי תטא","8 דקות","16303","video","https://player.vimeo.com/video/665873220?h=532b632459&dnt=1"],
["יסודות תטא","עקומת תטא אופציית Call","4 דקות","16304","video","https://player.vimeo.com/video/665875253?h=b2b60b7fc6&dnt=1"],
["דעיכת זמן — קונים","השפעת דעיכת הזמן על קונה אופציית Call","2 דקות","16305","video","https://player.vimeo.com/video/665876937?h=a2ee660aeb&dnt=1"],
["דעיכת זמן — קונים","עקומת תטא אופציית Put","3 דקות","16306","video","https://player.vimeo.com/video/665922814?h=8527c2901d&dnt=1"],
["דעיכת זמן — קונים","השפעת דעיכת הזמן על קונה אופציית Put","5 דקות","16307","video","https://player.vimeo.com/video/666036691?h=909d425ddb&dnt=1"],
["דעיכת זמן — מוכרים","השפעת דעיכת הזמן על מוכר אופציית Put","7 דקות","16309","video","https://player.vimeo.com/video/666048436?h=f18f8382c8&dnt=1"],
["פקיעה ומיקום האופציה","תטא ותאריכי פקיעה שונים","6 דקות","16310","video","https://player.vimeo.com/video/666228112?h=6ef61ab2c6&dnt=1"],
["פקיעה ומיקום האופציה","תטא ואופצייה מחוץ לכסף","7 דקות","16311","video","https://player.vimeo.com/video/666231481?h=f2cbdc3fa7&dnt=1"],
["פקיעה ומיקום האופציה","תטא ואופצייה בתוך הכסף","5 דקות","16312","video","https://player.vimeo.com/video/666233061?h=dc84ebc940&dnt=1"],
["תטא בתיק","תטא של תיק","7 דקות","16313","video","https://player.vimeo.com/video/666451580?h=c036b35a45&dnt=1"],
["תטא בתיק","תטא של מניה","3 דקות","16314","video","https://player.vimeo.com/video/666451631?h=d9958cb424&dnt=1"],
["יישום באסטרטגיות","דוגמאות של ערך הזמן על אסטרטגיות באופציות 1","6 דקות","16315","video","https://player.vimeo.com/video/666407442?h=edd9f3037a&dnt=1"],
["יישום באסטרטגיות","דוגמאות של ערך הזמן על אסטרטגיות באופציות 2","6 דקות","16316","video","https://player.vimeo.com/video/666407422?h=6d3364e7d0&dnt=1"],
["יישום באסטרטגיות","דוגמאות של ערך הזמן על אסטרטגיות באופציות 3","4 דקות","16317","video","https://player.vimeo.com/video/666407391?h=b1e06a85e2&dnt=1"],
["יישום באסטרטגיות","דוגמאות של ערך הזמן על אסטרטגיות באופציות 4","6 דקות","16318","video","https://player.vimeo.com/video/666407355?h=5936ebc404&dnt=1"],
["סיכום ומעבר לרמה 6","קורס מסחר באופציות: רמה 6 – תנודתיות ווגא","שיעור טקסט","16319","text",""]
];
const endHtml=`<h3>מעבר מקורס תטא לקורס ווגא</h3><p>בקורס תטא העמקנו בהשפעת הזמן על ערך האופציה, בערך פנימי וחיצוני ובאופן שבו דעיכת הזמן משפיעה על קונים ומוכרים של אופציות Call ו-Put.</p><p>בקורס הבא עוברים לתנודתיות ולווגא — הגורם שמתאר כיצד שינוי בתנודתיות משפיע על מחיר האופציה.</p><hr><h3>השלב הבא</h3><p>רמה 6 — תנודתיות ווגא.</p>`;
const $=id=>document.getElementById(id),total=L.length;
let current=Math.max(1,Math.min(total,parseInt(new URLSearchParams(location.search).get('lesson')||'1',10)));
const done=new Set(JSON.parse(localStorage.getItem('trade2-option5-done')||'[]'));
function renderList(){let html='',last='';L.forEach((x,i)=>{if(x[0]!==last){if(last)html+='</section>';last=x[0];html+=`<section class="syllabus-section"><h3>${x[0]}</h3>`}html+=`<div class="syllabus-item${i+1===current?' active':''}${done.has(i+1)?' done':''}" data-lesson="${i+1}"><span class="lesson-number">${i+1}</span><span class="lesson-check">${done.has(i+1)?'✓':''}</span><span class="lesson-copy"><strong>${x[1]}</strong><small>${x[2]} · ID ${x[3]}</small></span><span class="lesson-symbol">${x[4]==='text'?'▤':'▶'}</span></div>`});if(last)html+='</section>';$('syllabusList').innerHTML=html;document.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>go(+el.dataset.lesson));setTimeout(()=>document.querySelector('.syllabus-item.active')?.scrollIntoView({block:'nearest'}),20)}
function about(x){if(x[4]==='text')return 'סיכום רמה 5 והמעבר מתטא — השפעת הזמן — לרמה 6, שבה נלמד על תנודתיות ווגא.';if(x[0].includes('יסודות'))return `בשיעור זה נבין את ${x[1]} ואת הקשר בין חלוף הזמן לערך האופציה.`;if(x[0].includes('קונים'))return `השיעור בוחן את ${x[1]} מנקודת המבט של קונה האופציה וכיצד דעיכת הזמן משפיעה על הפוזיציה.`;if(x[0].includes('מוכרים'))return `השיעור בוחן את ${x[1]} מנקודת המבט של מוכר האופציה ואת המשמעות של הזמן עבור הפרמיה.`;if(x[0].includes('פקיעה'))return `בשיעור זה נלמד את ${x[1]} ונחבר בין תטא, זמן לפקיעה ומיקום האופציה ביחס לכסף.`;if(x[0].includes('תיק'))return `השיעור מעביר את מושג התטא מרמת אופציה בודדת להסתכלות על ${x[1]}.`;return `בשיעור זה ניישם את ערך הזמן דרך ${x[1]} ונראה כיצד תטא באה לידי ביטוי באסטרטגיות אופציות.`}
function load(){const x=L[current-1];$('lessonTitle').textContent=x[1];$('lessonType').textContent=x[4]==='text'?'שיעור טקסט':'שיעור וידאו';$('lessonMeta').textContent=`${x[2]} · WordPress ID ${x[3]}`;$('lessonIdTop').textContent=`ID ${x[3]}`;$('progressText').textContent=`שיעור ${current} מתוך ${total}`;$('progressBar').style.width=`${current/total*100}%`;$('factLesson').textContent=`${current} / ${total}`;$('factDuration').textContent=x[2];$('factSection').textContent=x[0];$('factId').textContent=x[3];$('aboutTitle').textContent=x[1];$('aboutText').textContent=about(x);$('prevBtn').disabled=current===1;$('nextBtn').disabled=current===total;$('videoCard').hidden=true;$('textCard').hidden=true;$('missingCard').hidden=true;if(x[4]==='text'){$('textCard').hidden=false;$('textLessonBody').innerHTML=endHtml;$('lessonFrame').src=''}else if(x[5]){$('videoCard').hidden=false;$('lessonFrame').src=x[5]}else{$('missingCard').hidden=false;$('lessonFrame').src=''};$('markComplete').textContent=done.has(current)?'הושלם ✓':'סמן כהושלם';renderList()}
function go(n){if(n<1||n>total)return;current=n;history.replaceState(null,'',`?lesson=${n}`);load();window.scrollTo({top:0,behavior:'smooth'})}
$('prevBtn').onclick=()=>go(current-1);$('nextBtn').onclick=()=>go(current+1);$('markComplete').onclick=()=>{done.add(current);localStorage.setItem('trade2-option5-done',JSON.stringify([...done]));if($('autoNext').checked&&current<total)go(current+1);else load()};
load();
