let st={q:'',c:'הכל',l:'הכל',o:'default'},g=document.getElementById('allCoursesGrid'),r=document.getElementById('resultCount'),q=document.getElementById('courseSearch'),o=document.getElementById('sortCourses');
const n=v=>parseInt(String(v||'').replace(/\D/g,''),10)||0;
const courseHref=x=>x.t.includes('קורס מסחר באופציות: רמה 1')?'/courses/option1/':'https://trade2.co.il/courses/';
function draw(){let a=C.filter(x=>{let z=st.q.trim().toLowerCase(),txt=(x.t+' '+x.c+' '+x.cs+' '+x.l).toLowerCase();return(!z||txt.includes(z))&&(st.c==='הכל'||x.c===st.c||x.cs.split('|').includes(st.c))&&(st.l==='הכל'||x.l===st.l)});if(st.o==='title')a.sort((a,b)=>a.t.localeCompare(b.t,'he'));if(st.o==='students')a.sort((a,b)=>n(b.s)-n(a.s));if(st.o==='views')a.sort((a,b)=>n(b.v)-n(a.v));r.textContent=a.length+' קורסים';const ac=document.getElementById('availableCourses');if(ac)ac.textContent=C.length;g.innerHTML=a.map(x=>{const href=courseHref(x),external=href.startsWith('http');return `<a class="course-card" href="${href}" ${external?'target="_blank" rel="noopener"':''}><div class="course-img"><img src="${x.i}" alt="${x.t.replace(/"/g,'&quot;')}" loading="lazy"></div><div class="course-body"><div class="card-top"><span class="tag">${x.c}</span>${x.l?`<span class="level">${x.l}</span>`:''}</div><h3>${x.t}</h3><div class="course-meta">${x.d?`<span>◷ ${x.d}</span>`:''}${x.s?`<span>👥 ${Number(x.s).toLocaleString('he-IL')}</span>`:''}</div></div></a>`}).join('')||'<div class="empty">לא נמצאו קורסים שמתאימים לחיפוש.</div>'}
function setCategory(btn){document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');st.c=btn?btn.dataset.category:'הכל';draw();}
document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b));
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('active'));b.classList.add('active');st.l=b.dataset.level;draw()});
document.querySelectorAll('[data-side-category]').forEach(a=>a.onclick=()=>{const cat=a.dataset.sideCategory;const btn=[...document.querySelectorAll('[data-category]')].find(x=>x.dataset.category===cat);if(btn)setCategory(btn);setTimeout(()=>document.getElementById('all-courses')?.scrollIntoView({behavior:'smooth'}),50)});
q.oninput=e=>{st.q=e.target.value;draw()};o.onchange=e=>{st.o=e.target.value;draw()};
function seedBars(){const wrap=document.getElementById('aiBars');if(!wrap)return;wrap.innerHTML='';for(let i=0;i<28;i++){const bar=document.createElement('i');bar.style.height=(18+Math.random()*70)+'%';wrap.appendChild(bar)}}
function tickBars(){const wrap=document.getElementById('aiBars');if(!wrap)return;const bar=document.createElement('i');bar.style.height=(18+Math.random()*72)+'%';bar.style.opacity='.25';wrap.appendChild(bar);requestAnimationFrame(()=>{bar.style.opacity='.85'});while(wrap.children.length>28)wrap.removeChild(wrap.firstElementChild)}
seedBars();setInterval(tickBars,1000);
draw();